CREATE OR REPLACE DATABASE TOKENIZER_DEMO;

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE DEMO_ANALYST;
CREATE OR REPLACE ROLE DEMO_DEVELOPER;

GRANT ROLE DEMO_ANALYST TO ROLE ACCOUNTADMIN;
GRANT ROLE DEMO_DEVELOPER TO ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE TOKENIZER_DEMO TO ROLE DEMO_ANALYST;
GRANT USAGE ON SCHEMA TOKENIZER_DEMO.PUBLIC TO ROLE DEMO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TOKENIZER_DEMO.PUBLIC TO ROLE DEMO_ANALYST;

GRANT USAGE ON DATABASE TOKENIZER_DEMO TO ROLE DEMO_DEVELOPER;
GRANT USAGE ON SCHEMA TOKENIZER_DEMO.PUBLIC TO ROLE DEMO_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TOKENIZER_DEMO.PUBLIC TO ROLE DEMO_DEVELOPER;

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE TOKENIZER_DEMO_WH;
GRANT USAGE ON WAREHOUSE TOKENIZER_DEMO_WH TO ROLE DEMO_ANALYST;
GRANT USAGE ON WAREHOUSE TOKENIZER_DEMO_WH TO ROLE DEMO_DEVELOPER;

CREATE OR REPLACE API INTEGRATION TOKENIZER_API
api_provider=aws_api_gateway    
api_aws_role_arn='{{ IAM_ROLE_ARN }}'    
api_allowed_prefixes=('https://xxxxx.execute-api.eu-west-1.amazonaws.com/dev/detokenize_string')
enabled=true;

DESCRIBE INTEGRATION TOKENIZER_API;
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))