DROP DATABASE IF EXISTS TOKENIZER_DEMO;
DROP ROLE IF EXISTS DEMO_ANALYST;
DROP ROLE IF EXISTS DEMO_DEVELOPER;

DROP WAREHOUSE IF EXISTS TOKENIZER_DEMO_WH;
DROP API INTEGRATION IF EXISTS TOKENIZER_API;